### ISSUE TITLE
Incompatible JNA native library error

### ISSUE THREAD

**Issue by metasoarous** [pallet/pallet#336]
I'm just starting to mess with pallet and have now had the following issue on two systems. Running through the "First Steps" tutorial, I get to the point creating a node and get stuck:

```
user=> (def s (pallet.api/converge {my-group 1} :compute aws))
Jul 11, 2014 3:30:04 PM clojure.tools.logging$eval376$fn__377 invoke
INFO: 54.191.103.73 22 os: infer-os: 
Jul 11, 2014 3:30:04 PM clojure.tools.logging$eval376$fn__377 invoke
WARNING: async-fsm failed
java.lang.Error: 

There is an incompatible JNA native library installed on this system.
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

        at com.sun.jna.Native.<clinit>(Native.java:142)
        at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary.<clinit>(JNAUSocketFactory.java:45)
        at com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory.open(JNAUSocketFactory.java:108)
        at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.open(SSHAgentConnector.java:80)
        at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:48)
        at clj_ssh.agent$sock_agent_connector.invoke(agent.clj:15)
```

Both removing the package (`sudo apt-get remove libjna-java`) and having java ignore jna via (via `:jvm-opts ["-Djna.nosys=true"]` in my project.clj) avoid this error, but now I get this:

```
user=> (def s (pallet.api/converge {my-group 1} :compute aws))

; machine 1
Jul 11, 2014 3:32:11 PM clojure.tools.logging$eval376$fn__377 invoke
INFO: 54.191.103.73 22 os: infer-os: 

: machine 2
17:05:13.202 [operate-24] INFO  pallet.ssh.execute - 54.191.103.73 22 os: infer-os:
```

... and then it hangs.

FWIW, I'm running `Leiningen 2.4.0 on Java 1.7.0_55 OpenJDK 64-Bit Server VM` on Ubuntu 14.04. Happy to share any more info that seems pertinent.
### I'm pretty this wasn't happening before...

Now, the strange thing is that while I still haven't managed to get past this step, I was actually having a different problem at this point until all of a sudden (corresponding to roughly the same time that I installed some updates from the software center), this issue started popping up. Before this started happening, I could see that nodes were getting launched in the AWS console, but shut down right away with some messages about conflicting credentials in the same classes (rough recollection). Now, it's not getting as far as firing up nodes, so I think this is something happening upstream of the problems I was having. I'm guessing it's really a separate issue, but I mention it in the interest of full disclosure, and of explaining that this didn't _seem_ to be the issue till just recently. If I get past this and am still having the other issue, I'll open up a separate ticket for the other thing.

**Comment by edidada** [comment]
I also meet this problem

**Comment by jerger** [comment]
Last time I tried, com.jcraft was quite outdated. Maybe my workaround is useful to you: 

I'm using hashicorp terraform for managing (e.g. create) instances,
hand over the ip's of generated instances & 
use pallet to provision them over ssh ... 

For Image-creation I use hashicorp packer and pallet localhost provisioning.
